# Generated by Django 5.1.5 on 2025-01-17 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('seater', models.IntegerField()),
                ('car_type', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=50)),
                ('transmission', models.CharField(max_length=50)),
                ('fuel_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('out_of_order', 'Out of Order')], default='available', max_length=20)),
                ('details', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255, null=True)),
                ('brand', models.CharField(max_length=255)),
                ('total_count', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('colors', models.JSONField()),
                ('transmission', models.JSONField()),
                ('fuel_type', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('chauffeur', 'Chauffeur'), ('self', 'Self')], max_length=10)),
                ('booking_time', models.DateTimeField()),
                ('pickup_time', models.DateTimeField()),
                ('drop_time', models.DateTimeField()),
                ('total_price', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.user')),
                ('fleet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='fleet.fleet')),
            ],
        ),
        migrations.AddField(
            model_name='fleet',
            name='inv_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='fleet.inventory'),
        ),
    ]
